version: '3.8'

services:
  web:
    build: ./app
    container_name: siakad_web
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./app/siakad:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=siakad

  db:
    image: mysql:5.7
    container_name: siakad_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:3306"

volumes:
  db_data:
